#install haproxy packages
- name: Install haproxy
  yum: name haproxy state=installed

- name: copy base configure over.
  file: src=haproxy/haproxy_base.cfg dest=/etc/haproxy/haproxy.cfg


- name: Add vip for loadbalance
  shell: pcs resource create loadbalancer-{{lb_vip}} ocf:heartbeat:IPaddr2 ip={{mariadb_vip}} cidr_netmask=32 op monitor interval=30s

- name: add pcs resource for LB
  shell: pcs resource create lb-haproxy --group haproxy systemd:haproxy op monitor interval=10s

- name: contraints for LB
  shell: pcs constraint {{ item }}
  with_items:
    - colocation add lb-haproxy loadbalancer-{{lb_vip}}
    - order loadbalancer-{{lb_vip}} lb-haproxy
