
# setup basic pacemaker
- name: pcs auth
  shell: echo pcs cluster auth {{ hostvars[item]['ansible_hostname'] }}  -u hacluster -p password
  with_items:
    - groups.openstack_controller


#- name: create cluster
#  shell: pcs cluster setup --name osp-control-cluster controller-1.novalocal controller-2.novalocal controller-3.novalocal --force --start
