# copy sysctl settings
- name: copy 99-sysctl.conf
  copy: src=sysctl.conf dest=/etc/sysctl.d/99-sysctl.conf owner=root group=root mode=0644 force

- name: load sysctl
  shell: sysctl -p /etc/sysctl.d/99-sysctl.conf


- include: haproxy.yml
# Install the DB services
- include: mariadb.yml
