# copy sysctl settings
- name: copy 99-sysctl.conf
  copy: src=sysctl.conf dest=/etc/sysctl.d/99-sysctl.conf owner=root group=root mode=0644 force

# Install the controller services
- include: mariadb.yml
