- debug: msg="head_node={{head_node}}"
- debug: msg="fqdn = {{ ansible_fqdn }}"

#This installs and configures Mariadb
- name: Install MariaDB
  yum: name={{ item }} state=installed
  with_items:
    - mariadb
    - mariadb-galera-server
    - mariadb-galera-common
    - mariadb-libs

- name: copy configuration files for MariaDB
  file: src={{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644 seuser=system_u serole=object_r setype=mysqld_etc_t selevel=s0
  with_items:
    - my.cnf
    - my.cnf.d/client.cnf
    - my.cnf.d/galera.cnf
    - my.cnf.d/mysql-clients.cnf
    - my.cnf.d/server.cnf

- name: Start the galera on controller-1
  shell: 'mysqld --wsrep_cluster_address=gcomm:// &'
  when: {{ansible_fqdn}} == {{head_node}}

- name: configure mariaDB:pacemaker:create vip
  shell: 'pcs resource create vip_mariadb_galera ocf:heartbeat:IPaddr2 params nic="eth1" iflabel="galera" ip="{{mariadb_vip}}" cidr_netmask="24"'
  when: {{ansible_fqdn}} == {{head_node}}

- name: configure mariaDB:pacemaker:create galera resource
  shell: 'pcs resource create mariadb_galera ocf:heartbeat:mysql params config="/etc/mysql/my.cnf" pid="/var/run/mysqld/mysqld.pid" socket="/var/run/mysqld/mysqld.sock" binary="/usr/sbin/mysqld"   op monitor interval="30s" op start interval="0" timeout="60s" op stop interval="0" timeout="60s"'
  when: {{ansible_fqdn}} == {{head_node}}

- name: configure mariaDB:pacemaker:create galera clone
  shell: 'pcs resource clone clone_mariadb mariadb_galera meta interleave="true"'
  when: {{ansible_fqdn}} == {{head_node}}

- name: configure mariaDB:pacemaker:create galera colocation
  shell: 'pcs resource colocation c_ip_galera_on_mariadb inf vip_mariadb_galera clone_mariadb'
  when: {{ansible_fqdn}} == {{head_node}}

#add iptables rules for galera and mysql
