#This installs and configures Mariadb
- name: install mariadb and galara

- name: Install MariaDB
  yum: name={{ item }} state=installed
    - mariadb
    - mariadb-galera-server
    - mariadb-galera-common
    - mariadb-libs

- name: copy configuration files for MariaDB
  file: src={{ item }} dest=/etc/{{ item }} owner=root group=root mode=0644 seuser=system_u serole=object_r setype=mysqld_etc_t selevel=s0
  with_items:
    - my.cnf
    - my.cnf.d/client.cnf
    - my.cnf.d/galera.cnf
    - my.cnf.d/mysql-clients.cnf
    - my.cnf.d/server.cnf
