#{% set head_node = hostvars[groups['openstack_controller'][0]] %}
#{% set node1 = hostvars[groups['openstack_controller'][1]] %}
#{% set node2 = hostvars[groups['openstack_controller'][2]] %}
#Install Pacemaker and configure

- name: Install pacemaker
  yum: name={{ item }} state=present
  with_items:
    - pacemaker
#    - cman
    - pcs
    - resource-agents

- name: setup hacluster passwd
  user: name=hacluster comment='pacemkaers user'

- name: create password for hacluster
  shell: echo {{ all_password }} | passwd hacluster --stdin


- name: start pcsd
  service: name=pcsd state=started enabled=yes
