# subscribe a RHEL7 system to RHN

- name: register to RHN
  shell: subscription-manager register --username={{rhn-user}} --password={{rhn-pass}}

- name: attach to pool
  shell: subscription-manager attach {{pool}}

- name: enable repos
  shell: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-openstack-6.0-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-ha-for-rhel-7-server-rpms
